### ISSUE TITLE
PlatformException in android init

### ISSUE THREAD

**Issue by cyz1901** [material-foundation/google-fonts-flutter#275]
Hello team, when i use
```
MaterialApp.router(
          theme: ThemeData(
            textTheme: GoogleFonts.vollkornTextTheme()
          ),
          routerConfig: Routers.router,
        );
```
in android 33 device i found
```
W/Parcel  (13038): Expecting binder but got null!
E/flutter (13038): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13038): #0      PathProviderApi.getApplicationSupportPath (package:path_provider_android/messages.g.dart:74:7)
E/flutter (13038): <asynchronous suspension>
E/flutter (13038): #1      getApplicationSupportDirectory (package:path_provider/path_provider.dart:77:24)
E/flutter (13038): <asynchronous suspension>
E/flutter (13038): #2      _localPath (package:google_fonts/src/file_io_desktop_and_mobile.dart:40:21)
E/flutter (13038): <asynchronous suspension>
E/flutter (13038): #3      _localFile (package:google_fonts/src/file_io_desktop_and_mobile.dart:45:16)
E/flutter (13038): <asynchronous suspension>
E/flutter (13038): #4      saveFontToDeviceFileSystem (package:google_fonts/src/file_io_desktop_and_mobile.dart:15:16)
E/flutter (13038): <asynchronous suspension>
E/flutter (13038): 
```

```
Framework • revision eb6d86ee27 • 2022-10-04 22:31:45 -0700
Engine • revision c08d7d5efc
Tools • Dart 2.18.2 • DevTools 2.15.0
```

```
OS: Manjaro Linux x86_64
```

**Comment by cyz1901** [comment]
oh i found it is android plugin problem
